"""empty message

Revision ID: 0f8f6e6ac85f
Revises: e8b65ac95653
Create Date: 2025-04-06 12:18:48.586679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8f6e6ac85f'
down_revision = 'e8b65ac95653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.alter_column('nota_housekeeper',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalizado_por', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.drop_column('finalizado_por')

    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.alter_column('nota_housekeeper',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
