"""empty message

Revision ID: 1660beae78b5
Revises: 2c5a43dcc60d
Create Date: 2025-03-21 06:58:12.266132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1660beae78b5'
down_revision = '2c5a43dcc60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.drop_column('condition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
