"""empty message

Revision ID: 27466c8440b5
Revises: 826c431f6eb2
Create Date: 2025-04-24 19:08:06.219168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27466c8440b5'
down_revision = '826c431f6eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('housekeeper_id_branche_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])
        batch_op.drop_column('id_branche')

    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('housekeeper_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('housekeepertask_id_housekeeper_fkey', type_='foreignkey')
        batch_op.drop_constraint('housekeepertask_id_room_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'housekeeper', ['housekeeper_id'], ['id'])
        batch_op.create_foreign_key(None, 'room', ['room_id'], ['id'])
        batch_op.drop_column('id_room')
        batch_op.drop_column('id_housekeeper')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_housekeeper', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_room', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('housekeepertask_id_room_fkey', 'room', ['id_room'], ['id'])
        batch_op.create_foreign_key('housekeepertask_id_housekeeper_fkey', 'housekeeper', ['id_housekeeper'], ['id'])
        batch_op.drop_column('housekeeper_id')
        batch_op.drop_column('room_id')

    with op.batch_alter_table('housekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_branche', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('housekeeper_id_branche_fkey', 'branches', ['id_branche'], ['id'])
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
