"""empty message

Revision ID: 437cddda2144
Revises: e596c5306a02
Create Date: 2025-03-06 08:53:26.736236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437cddda2144'
down_revision = 'e596c5306a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoteles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hoteles')
    # ### end Alembic commands ###
