"""empty message

Revision ID: 88975b09d7b5
Revises: 1ed5cbd424b1
Create Date: 2025-03-10 18:50:22.717273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88975b09d7b5'
down_revision = '1ed5cbd424b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housekeeper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('id_branche', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_branche'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('housekeeper')
    # ### end Alembic commands ###
