"""empty message

Revision ID: a9b39288b98b
Revises: 48fd2dd26d63
Create Date: 2025-03-09 21:41:13.267711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b39288b98b'
down_revision = '48fd2dd26d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoteltheme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_hoteles', sa.Integer(), nullable=True),
    sa.Column('id_theme', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_hoteles'], ['hoteles.id'], ),
    sa.ForeignKeyConstraint(['id_theme'], ['theme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hoteltheme')
    # ### end Alembic commands ###
