"""empty message

Revision ID: b32c80b7edd7
Revises: 57a1c5ae7242
Create Date: 2025-03-18 07:27:54.238855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32c80b7edd7'
down_revision = '57a1c5ae7242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.drop_constraint('housekeepertask_nombre_key', type_='unique')
        batch_op.drop_constraint('housekeepertask_photo_key', type_='unique')

    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.drop_constraint('maintenancetask_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.create_unique_constraint('maintenancetask_nombre_key', ['nombre'])

    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.create_unique_constraint('housekeepertask_photo_key', ['photo'])
        batch_op.create_unique_constraint('housekeepertask_nombre_key', ['nombre'])

    # ### end Alembic commands ###
