"""empty message

Revision ID: b5f15565d67e
Revises: bfd871699560
Create Date: 2025-03-11 20:12:18.354195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f15565d67e'
down_revision = 'bfd871699560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('housekeepertask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=120), nullable=False),
    sa.Column('condition', sa.String(length=80), nullable=False),
    sa.Column('assignment_date', sa.String(length=80), nullable=False),
    sa.Column('submission_date', sa.String(length=80), nullable=False),
    sa.Column('id_room', sa.Integer(), nullable=True),
    sa.Column('id_housekeeper', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_housekeeper'], ['housekeeper.id'], ),
    sa.ForeignKeyConstraint(['id_room'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('photo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('housekeepertask')
    op.drop_table('room')
    # ### end Alembic commands ###
