"""empty message

Revision ID: c134c90abc5a
Revises: 0c5302e22b2a
Create Date: 2025-03-20 21:49:00.841016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c134c90abc5a'
down_revision = '0c5302e22b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.drop_column('condition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
