"""empty message

Revision ID: e8b65ac95653
Revises: 27a24ee82df4
Create Date: 2025-04-05 17:52:45.146668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b65ac95653'
down_revision = '27a24ee82df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_housekeeper', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeepertask', schema=None) as batch_op:
        batch_op.drop_column('nota_housekeeper')

    # ### end Alembic commands ###
