"""empty message

Revision ID: f9240f9bc5f2
Revises: 1660beae78b5
Create Date: 2025-03-23 21:20:47.583299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9240f9bc5f2'
down_revision = '1660beae78b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=120), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenancetask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
